Django_CRUD/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'crud_app'
urlpatterns = [
  
    path('admin/', admin.site.urls),
    path('crud_app/', include('crud_app.urls')),
    
]

crud_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import edit_dc_parts

app_name = 'crud_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_request, name='logout'),
    path('settings', views.settings, name='settings'),
    path('new_dc', views.new_dc, name='new_dc'),
    path('new_color', views.new_color, name='new_color'),
    path('new_furniture_type', views.new_furniture_type, name='new_furniture_type'),
    path('new_part_type', views.new_part_type, name='new_part_type'),
    path('new_part', views.new_part, name='new_part'),
    path('dc_parts', views.dc_parts, name='dc_parts'),
    path('all_dc_skus', views.all_dc_skus, name='all_dc_skus'),
    path('edit_dc_parts/<int:pk>/', views.edit_dc_parts, name='edit_dc_parts'),
    path('all_skus', views.all_skus, name='all_skus'),
    path('all_vendors', views.all_vendors, name='all_vendors'),
    path('new_vendor', views.new_vendor, name='new_vendor'),
    path('edit_vendors/<int:pk>/', views.edit_vendors, name='edit_vendors'),
    path('new_slat', views.new_slat, name='new_slat'),
    path('all_slat_info', views.all_slat_info, name='all_slat_info'),
    path('one_stop_shop', views.one_stop_shop, name='one_stop_shop'),
    path('generate_label/<int:pk>/', views.generate_label, name='generate_label'),
    path('new_inventory_transfer', views.new_inventory_transfer, name='new_inventory_transfer'),
    path('receive_inventory_transfer/', views.receive_inventory_transfer, name='receive_inventory_transfer'),
    path('process_transfer', views.process_transfer, name='process_transfer'),
    path('quick_scan', views.process_quick_scan, name='process_quick_scan'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crud_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.storage import DefaultStorage
# Create your models here.



class Vendors(models.Model):
    vendor_name = models.CharField(max_length=100 ,unique=True)
    vendor_id = models.CharField(max_length=4 ,unique=True)
    vendor_code = models.PositiveSmallIntegerField(unique=True)
    SEND_PART_CHOICES = [
        ('Yes', 'Yes'),
        ('No', 'No'),
    ]
    sends_parts = models.CharField(choices=SEND_PART_CHOICES, max_length=3, default='Yes')
    available_parts = models.CharField(max_length=500, blank=True)
    unavailable_parts = models.CharField(max_length=500, blank=True)
    part_shipping = models.CharField(max_length=400, blank=True)
    other_part_info = models.CharField(max_length=400, blank=True)

    def __str__(self):
        return f"{self.vendor_name} - {self.vendor_id}"
    
    def vendor_code_only(self):
        return f"{self.vendor_code}"
    
    def benchstock_items_count(self):
        return Benchstock_part.objects.filter(vendor=self).count()
    

class Furniture(models.Model):
    furniture_categories = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return f"{self.furniture_categories}"
    

class Parts(models.Model):
    part_categories = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return f"{self.part_categories}"
    
class Color(models.Model):
    color_options = models.CharField(max_length=30, unique=True)
    
    def __str__(self):
        return f"{self.color_options}"


class DC(models.Model):
    dc_name = models.CharField(max_length=80, unique=True)
    dc_number = models.PositiveSmallIntegerField(unique=True)
    rack_amount = models.SmallIntegerField()
    shelf_per_rack = models.SmallIntegerField()
    def __str__(self):
        return f"{self.dc_name} - {self.dc_number}" 
    

class Benchstock_part(models.Model):
    vendor = models.ForeignKey(Vendors, on_delete=models.SET_NULL, null=True)
    benchstock_sku = models.PositiveIntegerField(unique=True, editable=False)
    furniture_type = models.ManyToManyField(Furniture)
    part_type = models.ForeignKey(Parts, on_delete=models.SET_NULL, null=True)
    part_description = models.CharField(max_length=50, blank=True)
    part_color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True)
    part_image = models.ImageField(null=True, storage=DefaultStorage())
    ACTIVE_CHOICES =  [
        ('Active', 'Active'),
        ('Discontinued', 'Discontinued'),
    ]
    discontinued = models.CharField(choices=ACTIVE_CHOICES, max_length=30, default='Active')

    class Meta:
        unique_together = [['vendor','part_type','part_description','part_color']]

    def save(self, *args, **kwargs):
        if not self.pk:
            count = Benchstock_part.objects.filter(vendor=self.vendor).count() + 1
            self.benchstock_sku = int(f"{self.vendor.vendor_code}0850{count:02d}")
        super(Benchstock_part, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.vendor} - {self.benchstock_sku} - {self.part_color} - {self.part_type}"


class Benchstock_part_in_DC(models.Model):
    dc = models.ForeignKey(DC, on_delete=models.CASCADE)
    benchstock_part = models.ForeignKey(Benchstock_part, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    optimal_quantity = models.PositiveSmallIntegerField()
    rack_number = models.PositiveSmallIntegerField()
    shelf_number = models.PositiveSmallIntegerField()
    SELF_SIDE_CHOICES = [
        ('A','A'),
        ('B','B'),
    ]
    shelf_side = models.CharField(choices=SELF_SIDE_CHOICES, max_length=1)

    class Meta:
        unique_together = [['dc', 'benchstock_part']]
    
    def clean(self):
        if self.rack_number > self.dc.rack_amount:
            raise ValidationError({'rack_number': 'Rack Number is invalid, exceeds rack limit for DC'})
        if self.shelf_number > self.dc.shelf_per_rack:
            raise ValidationError({'shelf_number': 'Shelf Number is invalid, exceeds shelf limit for DC'})
        
    def __str__(self):
            return f"DC: {self.dc} SKU: {self.benchstock_part.benchstock_sku} Quantity: {self.quantity}"
    
class SlatInformation(models.Model):
    vendor = models.ForeignKey(Vendors, on_delete=models.SET_NULL, null=True)
    sku = models.PositiveIntegerField(unique=True)
    slat_amount = models.PositiveIntegerField(blank=True, null=True)
    slat_length = models.PositiveIntegerField(blank=True, null=True)
    center_slat_amount = models.PositiveIntegerField(blank=True, null=True)
    center_slat_length = models.PositiveIntegerField(blank=True, null=True)
    support_amount = models.PositiveIntegerField(blank=True, null=True)
    support_height = models.PositiveIntegerField(blank=True, null=True)
    mid_support_amount = models.PositiveIntegerField(blank=True, null=True)
    mid_support_height = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.vendor} - {self.sku}"
    

class InventoryTransfer(models.Model):
    transfer_number = models.AutoField(primary_key=True)
    to_dc = models.ForeignKey(DC, on_delete=models.CASCADE, related_name='to_dc')
    benchstock_part_in_dc = models.ForeignKey(Benchstock_part_in_DC, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()
    shipping_date = models.DateField(auto_now_add=True)
    received_date = models.DateField(blank=True, null=True)
    STATUS_CHOICES = [
        ('Lost', 'Lost'),
        ('Shipped', 'Shipped'),
        ('Received', 'Received'),
    ]
    status = models.CharField(max_length=30, default='Shipped', choices=STATUS_CHOICES)

    def __str__(self):
        return f"{self.transfer_number} - {self.benchstock_part_in_dc} - {self.quantity}"
    
    def clean(self):
        if self.benchstock_part_in_dc.dc == self.to_dc:
            raise ValidationError("From and To DC cannot be the same.")

class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_time = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=100)
    status = models.CharField(max_length=30)
    details = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return f"{self.user} - {self.date_time} - {self.action} - {self.status}"
    

crud_app/forms.py
from django import forms
from .models import Benchstock_part, Benchstock_part_in_DC, Vendors, DC, Color, Furniture, Parts, SlatInformation, InventoryTransfer
from django.core.exceptions import ValidationError



class VendorsForm(forms.ModelForm):
    class Meta:
        model = Vendors
        fields = ['vendor_name', 'vendor_id', 'vendor_code', 'sends_parts', 'available_parts', 'unavailable_parts', 'part_shipping', 'other_part_info']

class EditVendorForm(forms.ModelForm):
    class Meta:
        model = Vendors
        fields = ['sends_parts', 'available_parts', 'unavailable_parts', 'part_shipping', 'other_part_info']

class DCForm(forms.ModelForm):
    class Meta:
        model = DC
        fields = ['dc_name', 'dc_number', 'rack_amount', 'shelf_per_rack']

class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ['color_options']

class FurnitureForm(forms.ModelForm):
    class Meta:
        model = Furniture
        fields = ['furniture_categories'] 

class PartsForm(forms.ModelForm):
    class Meta:
        model = Parts
        fields = ['part_categories']

class BenchstockPartForm(forms.ModelForm):
    class Meta:
        model = Benchstock_part
        fields = ['vendor', 'furniture_type', 'part_type', 'part_description', 'part_color', 'part_image']
        # Exclude 'discontinued' from widgets as well since it's no longer a field in the form
        widgets = {
            'vendor': forms.Select(),
            'furniture_type': forms.CheckboxSelectMultiple(),
            'part_type': forms.Select(),
            'part_description': forms.TextInput(),
            'part_color': forms.Select(),
            'part_image': forms.FileInput(),
        }

    def __init__(self, *args, **kwargs):
        super(BenchstockPartForm, self).__init__(*args, **kwargs)
        self.fields['part_image'].required = False

class BenchstockDCPartForm(forms.ModelForm):
    class Meta:
        model = Benchstock_part_in_DC
        fields = ['dc','benchstock_part','quantity','optimal_quantity','rack_number','shelf_number','shelf_side']

class EditBenchstockPartInDCForm(forms.ModelForm):
    class Meta:
        model = Benchstock_part_in_DC
        fields = ['quantity', 'optimal_quantity', 'rack_number', 'shelf_number', 'shelf_side']


class SlatInformationForm(forms.ModelForm):
    class Meta:
        model = SlatInformation
        fields = ['vendor', 'sku', 'slat_amount', 'slat_length','center_slat_amount','center_slat_length','support_amount','support_height','mid_support_amount','mid_support_height']
       

class InventoryTransferForm(forms.ModelForm):
    class Meta:
        model = InventoryTransfer
        fields = ['to_dc', 'benchstock_part_in_dc', 'quantity']

    def clean(self):
        cleaned_data = super().clean()
        benchstock_part_in_dc = cleaned_data.get('benchstock_part_in_dc')
        quantity = cleaned_data.get('quantity')
        if benchstock_part_in_dc and quantity:
            if benchstock_part_in_dc.quantity < quantity:
                raise ValidationError({
                    'quantity': 'Insufficient quantity in source DC for transfer.'
                })

        return cleaned_data
    

crud_app/templates/crud_app/all_dc_skus.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'crud_app/css/alldcskus.css' %}">
{% endblock %}
{% block content %}
{%if user.is_authenticated%}
<div class="all-dc-skus-container">
    <form method="get" action="">
        <label for="dc_filter">Filter by DC:</label> 
        <select name="dc_filter">
            <option value="">--- Select DC ---</option>
            {% for dc in dc_choices %}
                <option value="{{ dc }}" {% if request.GET.dc_filter == dc %}selected{% endif %}>{{ dc }}</option>
            {% endfor %}
        </select>
    
        <label for="vendor_filter">Filter by Vendor:</label> 
        <select name="vendor_filter">
            <option value="">--- Select Vendor ---</option>
            {% for vendor in vendor_choices %}
                <option value="{{ vendor }}" {% if request.GET.vendor_filter == vendor %}selected{% endif %}>{{ vendor }}</option>
            {% endfor %}
        </select>
    
        <!-- Add more dropdowns as needed -->
        <input type="submit" value="Search">
    </form>
    <div class="all-dc-skus-table-wrapper">
        
        <table class="all-dc-skus-table">
            <thead>
                <tr>
                    <th>DC</th>
                    <th>Vendor</th>
                    <th>SKU</th>
                    <th>Furniture Type</th>
                    <th>Part Type</th>
                    <th>Part Description</th>
                    <th>Part Color</th>
                    <th>Part Image</th>
                    <th>Quantity</th>
                    <th>Optimal Quantity</th>
                    <th>Location</th>
                    <th>Edit</th>
                    <th>Print</th>
                </tr>
            </thead>
            <tbody>
                {% for sku in benchstock_parts_in_dc %}
                <tr>
                    <td>{{sku.dc}}</td>
                    <td>{{sku.benchstock_part.vendor.vendor_id}}</td>
                    <td>{{sku.benchstock_part.benchstock_sku}}</td>
                    <td>
                        {% for furniture in sku.benchstock_part.furniture_type.all %}
                        {{ furniture }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                </td>
                    <td>{{sku.benchstock_part.part_type}}</td>
                    <td>{{sku.benchstock_part.part_description}}</td>
                    <td>{{sku.benchstock_part.part_color}}</td>
                    <td>
                        {% if sku.benchstock_part.part_image %}
                            <a href="{{ sku.benchstock_part.part_image.url }}" target="_blank">{{ sku.benchstock_part.part_image }}</a>
                        {% else %}
                            No Image
                        {% endif %}
                    </td>
                    <td>{{sku.quantity}}</td>
                    <td>{{sku.optimal_quantity}}</td>
                    <td>{{sku.rack_number}}-{{sku.shelf_number}}-{{sku.shelf_side}}</td>
                    <td><a href="{% url 'crud_app:edit_dc_parts' sku.id %}">Edit</a></td>
                    <td><a href="{% url 'crud_app:generate_label' sku.id %}">Label PDF</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{%else%}
{%endif%}
{% endblock %}

crud_app/templates/crud_app/all_vendors.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'crud_app/css/allvendors.css' %}">
{% endblock %}
{% block content %}
{%if user.is_authenticated%}
<div class="all-vendors-container">
    <div class="all-vendors-table-wrapper">
        <table class="all-vendors-table">
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Vendor ID</th>
                    <th>Vendor Code</th>
                    <th>Sends Parts</th>
                    <th>Available Parts</th>
                    <th>Unavailable Parts</th>
                    <th>Part Shipping</th>
                    <th>Other Part Info</th>
                    <th>Edit</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for vendor in vendors %}
                <tr>
                    <td>{{vendor.vendor_name}}</td>
                    <td>{{vendor.vendor_id}}</td>
                    <td>{{vendor.vendor_code}}</td>
                    <td>{{vendor.sends_parts}}</td>
                    <td>{{vendor.available_parts}}</td>
                    <td>{{vendor.unavailable_parts}}</td>
                    <td>{{vendor.part_shipping}}</td>
                    <td>{{vendor.other_part_info}}</td>
                    <td><a href="{% url 'crud_app:edit_vendors' vendor.id %}">Edit</a></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{%else%}
{%endif%}
{% endblock %}

crud_app/templates/crud_app/new_part.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'crud_app/css/newpart.css' %}">
{% endblock %}
{% block content %}
{%if user.is_authenticated%}
<div class="new-part-form">
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 id="new-part-header">Add New Part:</h2><br>
        <div class="form-row">
            <div class="form-column">
        <label class="form-label">Vendor:</label>
        {{ form.vendor }} <br>
    
        <label class="form-label">Furniture Type:</label>
        <div class="scrollable-checkboxes">
            {% for checkbox in form.furniture_type %}
            <div class="checkbox-inline">
                {{ checkbox.tag }}  <!-- This is the actual checkbox input -->
                <label for="{{ checkbox.id_for_label }}">{{ checkbox.choice_label }}</label>
            </div>
        {% endfor %}
        </div><br>
    
        <label class="form-label" for="id_part_type">Part Type:</label>
        {{ form.part_type }} <br><br>
            </div>
            <div class="form-column">
        <label class="form-label" for="id_part_color">Part Color:</label>
        {{ form.part_color }} <br>
        <label class="form-label" for="id_part_description">Part Description:</label>
        {{ form.part_description }} <br><br><br>
        <label class="form-label" for="id_part_image">Part Image:</label>
        {{ form.part_image }} <br><br>
            </div>
        </div>
        {% if success_message %}
        <p class="success">{{ success_message }}</p>
        {% endif %}

    
        <button class="new-part-form-button">Save Part</button>
    </form>
</div>
{%else%}
{%endif%}
{% endblock %}

crud_app/templates/crud_app/one_stop_shop.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'crud_app/css/onestopshop.css' %}">
{% endblock %}
{% block content %}
{%if user.is_authenticated%}
<div class="oss-container">
    <h1 class="oss-title">One-Stop-Shop</h1>
    <form method="get" action="">
        <label for="dc_filter">Filter by DC:</label> 
        <select name="dc_filter">
            <option value="">--- Select DC ---</option>
            {% for dc in dc_choices %}
                <option value="{{ dc }}" {% if request.GET.dc_filter == dc %}selected{% endif %}>{{ dc }}</option>
            {% endfor %}
        </select>
    
        <label for="vendor_filter">Filter by Vendor:</label> 
        <select name="vendor_filter">
            <option value="">--- Select Vendor ---</option>
            {% for vendor in vendor_choices %}
                <option value="{{ vendor }}" {% if request.GET.vendor_filter == vendor %}selected{% endif %}>{{ vendor }}</option>
            {% endfor %}
        </select>

        <label for="sku_filter">Search by SKU:</label> 
        <input class="sku-input" type="text" name="sku_filter" value="{{ request.GET.sku_filter }}">

        <input class="submit-btn" type="submit" value="Search">

        <a href="{% url 'crud_app:one_stop_shop' %}" class="reset-btn"><i class="bi bi-arrow-clockwise"></i></a>
        {% if request.GET.sku_filter %}
        <div id="link-container">
            <a href="https://product-imaging.intra.cityfurniture.io/products/skuinformation/{{ request.GET.sku_filter }}" target="_blank">View CFE Imaging for {{ request.GET.sku_filter }}</a>
        </div>
        <div id="link-container">
            <a href="https://www.cityfurniture.com/catalogsearch/result?q={{ request.GET.sku_filter }}" target="_blank">View CityFurniture.com result {{ request.GET.sku_filter }}</a>
        </div>
        <div id="link-container">
            <a href="https://www.cityfurniture.com/catalogsearch/result?q={{ request.GET.sku_filter|slice:':4' }}" target="_blank">View CityFurniture.com related results {{ request.GET.sku_filter|slice:':4' }}</a>
        </div>
    {% endif %}
    </form>
    <div class="all-slats-table-wrapper">
        
        <table class="all-slats-table">
            <thead>
                <tr>
                    <th colspan="10" style="background-color: black; font-size: 1.7rem;">Slat Information:</th>
                </tr>
                <tr>
                    <th>Vendor</th>
                    <th>SKU</th>
                    <th>Slat Quantity</th>
                    <th>Slat Length</th>
                    <th>Center Slat Quantity</th>
                    <th>Center Slat Length</th>
                    <th>Support Quantity</th>
                    <th>Support Height</th>
                    <th>Mid Support Quantity</th>
                    <th>Mid Support Height</th>
                </tr>
            </thead>
            <tbody>
                {% for slats in slat_info %}
                <tr>
                    <td>{{slats.vendor}}</td>
                    <td>{{slats.sku}}</td>
                    <td>{{slats.slat_amount}}</td>
                    <td>{{slats.slat_length}}</td>
                    <td>{{slats.center_slat_amount}}</td>
                    <td>{{slats.center_slat_length}}</td>
                    <td>{{slats.support_amount}}</td>
                    <td>{{slats.support_height}}</td>
                    <td>{{slats.mid_support_amount}}</td>
                    <td>{{slats.mid_support_height}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="all-vendors-table-wrapper">
        <table class="all-vendors-table">
            <thead>
                <tr>
                    <th colspan="9" style="background-color: black; font-size: 1.7rem;">Vendor Information:</th>
                </tr>

                <tr>
                    <th>Vendor</th>
                    <th>Vendor ID</th>
                    <th>Vendor Code</th>
                    <th>Sends Parts</th>
                    <th>Available Parts</th>
                    <th>Unavailable Parts</th>
                    <th>Part Shipping</th>
                    <th>Other Part Info</th>
                    <th>Edit</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for vendor in vendors %}
                <tr>
                    <td>{{vendor.vendor_name}}</td>
                    <td>{{vendor.vendor_id}}</td>
                    <td>{{vendor.vendor_code}}</td>
                    <td>{{vendor.sends_parts}}</td>
                    <td>{{vendor.available_parts}}</td>
                    <td>{{vendor.unavailable_parts}}</td>
                    <td>{{vendor.part_shipping}}</td>
                    <td>{{vendor.other_part_info}}</td>
                    <td><a href="{% url 'crud_app:edit_vendors' vendor.id %}">Edit</a></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="all-dc-skus-table-wrapper">
        
        <table class="all-dc-skus-table">
            <thead>
                <tr>
                    <th colspan="12" style="background-color: black; font-size: 1.7rem;">Benchstock Inventory:</th>
                </tr>
                <tr>
                    <th>DC</th>
                    <th>Vendor</th>
                    <th>SKU</th>
                    <th>Furniture Type</th>
                    <th>Part Type</th>
                    <th>Part Description</th>
                    <th>Part Color</th>
                    <th>Part Image</th>
                    <th>Quantity</th>
                    <th>Optimal Quantity</th>
                    <th>Location</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                {% for sku in benchstock_parts_in_dc %}
                <tr>
                    <td>{{sku.dc}}</td>
                    <td>{{sku.benchstock_part.vendor.vendor_id}}</td>
                    <td>{{sku.benchstock_part.benchstock_sku}}</td>
                    <td>
                        {% for furniture in sku.benchstock_part.furniture_type.all %}
                        {{ furniture }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                </td>
                    <td>{{sku.benchstock_part.part_type}}</td>
                    <td>{{sku.benchstock_part.part_description}}</td>
                    <td>{{sku.benchstock_part.part_color}}</td>
                    <td>
                        {% if sku.benchstock_part.part_image %}
                            <a href="{{ sku.benchstock_part.part_image.url }}" target="_blank">{{ sku.benchstock_part.part_image }}</a>
                        {% else %}
                            No Image
                        {% endif %}
                    </td>
                    <td>{{sku.quantity}}</td>
                    <td>{{sku.optimal_quantity}}</td>
                    <td>{{sku.rack_number}}-{{sku.shelf_number}}-{{sku.shelf_side}}</td>
                    <td><a href="{% url 'crud_app:edit_dc_parts' sku.id %}">Edit</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    
</div>


{%else%}
{%endif%}
{% endblock %}

crud_app/templates/crud_app/settings.html
{% extends 'crud_app/base.html' %}
{% load static %}
{% block additional_css %}
<link rel="stylesheet" href="{% static 'crud_app/css/settings.css' %}">
{% endblock %}
{% block content %}
{%if user.is_authenticated%}
<div class="setting-forms-container">
    <div id="dc-settings" class="setting-forms">
        <h3>Distribution Centers</h3>
        <div class="scrollable-table-wrapper">
        <table class="setting-forms-table">
            <thead>
                <tr>
                    <th>Location</th>
                    <th>DC Number:</th>
                    <th>Rack Amount:</th>
                    <th>Shelf Per Rack:</th>
                </tr>
            </thead>
            <tbody>
                {% for dc in dcs %}
                <tr>
                    <td>{{dc.dc_name}}</td>
                    <td>{{dc.dc_number}}</td>
                    <td>{{dc.rack_amount}}</td>
                    <td>{{dc.shelf_per_rack}}</td>
                </tr>
                {% endfor %}
        </table>
        </div>
        <a class="setting-forms-button" href="{% url 'crud_app:new_dc' %}">Add DC</a>

    </div>
    <div id="color-settings" class="setting-forms">
        <h3>Color Options</h3>
        <div class="scrollable-table-wrapper">
        <table class="setting-forms-table">
            <thead>
                <tr>
                    <th>Color Name</th>
                </tr>
            </thead>
            <tbody>
                {% for color in colors %}
                <tr>
                    <td>{{color.color_options}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        <a class="setting-forms-button" href="{% url 'crud_app:new_color' %}">Add Color</a>
    </div>
    <div id="furniture-settings" class="setting-forms">
        <h3>Furniture Categories</h3>
        <div class="scrollable-table-wrapper">
        <table class="setting-forms-table">
            <thead>
                <tr>
                    <th>Category Name</th>
                </tr>
            </thead>
            <tbody>
                {% for furniture in furniture_categories %}
                <tr>
                    <td>{{furniture.furniture_categories}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        <a class="setting-forms-button" href="{% url 'crud_app:new_furniture_type' %}">Add Furniture Category</a>
    </div>
    <div id="part-settings" class="setting-forms">
        <h3>Part Types</h3>
        <div class="scrollable-table-wrapper">
        <table class="setting-forms-table">
            <thead>
                <tr>
                    <th>Part Type</th>
                </tr>
            </thead>
            <tbody>
                {% for part in part_categories %}
                <tr>
                    <td>{{part.part_categories}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        <a class="setting-forms-button" href="{% url 'crud_app:new_part_type' %}">Add Part Type</a>
    </div>
</div>
{%else%}

{%endif%}


{% endblock %}